fixed wx 3.0 vs 2.8 issue, introduced in 3d689ef6 Error fix regarding wxStandardPaths
* Get returns a wxStandardPathsBase, not wxStandardPaths
* jenkins build failure: https://jenkins.ciphershed.client.pdinc.us/job/ciphershed-0.3.7.0-dev-64bit-centos6-application/5/
** Compiling Application.cpp
** TextUserInterface.h: In static member function ‘static CipherShed::FilePath CipherShed::Application::GetConfigFilePath(const wxString&, bool)’:
** TextUserInterface.h:108: error: invalid initialization of reference of type ‘wxStandardPaths&’ from expression of type ‘wxStandardPathsBase’
** make[1]: *** [Application.o] Error 1
** make: *** [all] Error 2